# Generated by Django 4.2.21 on 2025-06-04 00:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo_area', models.CharField(max_length=50)),
                ('responsable_seguimiento', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_estimacion', models.DateTimeField()),
                ('estatus', models.CharField(default='En revisión', max_length=50)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estatus', models.CharField(default='Pendiente', max_length=50)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='gestor.solicitud')),
            ],
        ),
    ]
