# Generated by Django 4.2.21 on 2025-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_solicitud_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('otro', 'Otro')], default='media', max_length=20),
        ),
    ]
